### ISSUE TITLE
Cache Haskell builds

### ISSUE THREAD

**Issue by mariari** [anoma/juvix-stdlib#141]
the CI takes over 15 minutes to run simple topics:

https://github.com/anoma/juvix-stdlib/actions/runs/11716928476/job/32635794732?pr=139

I'm leaving this issue here, for me to eventually investigate, as I should make a PR to address this:

```yaml
      - name: Restore dependencies cache
        id: deps-cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            deps
            _build
          key: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
```

Here is the Anoma one
